name: Build cuOpt link for GAMS

on:
  push:
#    branches: [main]
    tags:
      - '*'        # Run also when a tag is pushed
  pull_request:

jobs:
  build-link:
    runs-on: ubuntu-latest
    container:
      image: python:3.12

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          apt-get update && apt-get install -y patchelf curl unzip zip gcc

      - name: Set up python virtual environment with NVIDIA dependencies
        run: |
          mkdir -p venvs
          python -m venv venvs/cu12
          bash -c "source venvs/cu12/bin/activate && \
            pip install --upgrade pip -qq && \
            pip install --extra-index-url=https://pypi.anaconda.org/rapidsai-wheels-nightly/simple/ cuopt-cu12==25.10.0 nvidia-cuda-runtime-cu12==12.8.* nvidia-nvjitlink-cu12 -qq"

      - name: Download and extract latest GAMS distribution
        run: |
          curl https://d37drm4t2jghv5.cloudfront.net/distributions/latest/linux/linux_x64_64_sfx.exe --output linux_x64_64_sfx.exe
          unzip -q linux_x64_64_sfx.exe
          mv gams*_linux_x64_64_sfx gamsdist
          rm linux_x64_64_sfx.exe

      - name: Compile gmscuopt
        run: |
          export GAMSCAPI="gamsdist/apifiles/C/api"
          export CUOPT="venvs/cu12/lib/python3.12/site-packages/libcuopt"
          export JITLINK="venvs/cu12/lib/python3.12/site-packages/nvidia/nvjitlink/lib"
          export CUOPT_VERSION="`cat $CUOPT/VERSION`"
          export CUOPT_HASH="`cat $CUOPT/GIT_COMMIT`"
          gcc -Wall gmscuopt.c -o gmscuopt.out \
            -DCUOPT_VERSION=$CUOPT_VERSION -DCUOPT_HASH=$CUOPT_HASH \
            -I $GAMSCAPI $GAMSCAPI/gmomcc.c $GAMSCAPI/optcc.c $GAMSCAPI/gevmcc.c \
            -I $CUOPT/include $JITLINK/libnvJitLink.so.12 -L $CUOPT/lib64 -lcuopt
          patchelf --set-rpath \$ORIGIN gmscuopt.out

      - name: Prepare release artifact
        run: |
          mkdir release
          cp gmscuopt.out release/
          cp assets/* release/
          cp venvs/cu12/lib/python3.12/site-packages/libcuopt/lib64/libcuopt.so release/
          cp venvs/cu12/lib/python3.12/site-packages/libcuopt/lib64/libmps_parser.so release/
          cp venvs/cu12/lib/python3.12/site-packages/libcuopt_cu12.libs/libgomp-5fc1ad8c.so.1.0.0 release/
          cp venvs/cu12/lib/python3.12/site-packages/rapids_logger/lib64/librapids_logger.so release/
          cp venvs/cu12/lib/python3.12/site-packages/librmm/lib64/librmm.so release/

      - name: Upload artifact to GitHub Actions (always)
        uses: actions/upload-artifact@v4
        with:
          name: cuopt-link
          path: release/

      - name: Create zip archive (only on tag push)
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          cd release
          zip -r ../cuopt-link-release.zip .

      - name: Create GitHub Release (only on tag push)
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: cuopt-link-release.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
